trigger:
  branches:
    include:
      - main
      - release
      - develop
      - uat

variables:
  # Container registry service connection established during pipeline creation
  tag: "$(Build.BuildId)"
  appName: "cibweb"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: BuildDEV
    displayName: Build DEV stage
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: "Use Node version"
            inputs:
              versionSpec: 16.13.2
          - task: Npm@1
            displayName: "npm angular cli"
            inputs:
              command: custom
              verbose: false
              customCommand: "install -g @angular/cli"
          - task: Npm@0
            displayName: "npm install"
            inputs:
              arguments: "--force"
          - task: Npm@1
            displayName: "npm build"
            inputs:
              command: custom
              verbose: false
              customCommand: "run build:dev"

  - stage: BuildUAT
    displayName: Build UAT stage
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: NodeTool@0
            displayName: "Use Node version"
            inputs:
              versionSpec: 16.13.2
          - task: Npm@1
            displayName: "npm angular cli"
            inputs:
              command: custom
              verbose: false
              customCommand: "install -g @angular/cli"
          - task: Npm@0
            displayName: "npm install"
            inputs:
              arguments: "--force"
          - task: Npm@1
            displayName: "npm build"
            inputs:
              command: custom
              verbose: false
              customCommand: "run build:dev"
