trigger:
  branches:
    include:
    - main
    - release
    - develop

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'acromnichannel'
  imageRepository: 'omnichannel/cibweb'
  containerRegistry: 'acromnichannel.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(system.defaultworkingdirectory)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - script: |
        wget https://download.defensecode.com/latest/clients/tscli.tar.gz -O tscli.tar.gz
        tar xvzf tscli.tar.gz
      displayName: 'Download/Extract ThunderScan API CLI'

    - script: |
        ./tscli --upload $(system.defaultworkingdirectory) --threshold "high:10" --engines 2 --report --formats "html,json" --filename "$(appName)-report" --name "$(appName)-$(tag)"
      displayName: 'ThunderScan Scan' 
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
