import { Injectable } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';

@Injectable()
export class CustomIconService {
  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {}
  init(): void {
    this.matIconRegistry.addSvgIcon(
      'account_information',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-account-information.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_back',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-arrow-back.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_up',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-arrow-up.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'arrow_down',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-arrow-down.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'appointment',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-appointment.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'calendar_day',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-calendar-day.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'caret_down',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-caret-down.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'caret_left',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-caret-left.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'caret_right',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-caret-right.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'chat',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-chat.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'check_round',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-check-round.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'close',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-close.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'edit',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-edit.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'colored-edit',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-colored-edit.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'help',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-help.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'hide_balance',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-hide-balance.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'localization',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Language.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'navigation_more',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-navigation-more.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'password',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-password.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'radio_button_off',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-radio-button-off.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'scheduled_payments',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-scheduled-payments.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'search',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-search.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'three_dots_on_grey',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/icon-button-three-dots-on-grey.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'three_dots_on_red',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/icon-button-three-dots-on-red.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'three_dots_on_white',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/icon-button-three-dots-on-white.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'unlink_account',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-unlink-account.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'view_statement',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-view-statement.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'three_dots',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/icon-button-more-on-white.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'home',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Home.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'transact',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-unselected-state-tran.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'lifestyle-unselected',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-unselected-state-life.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'lifestyle',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-selected-state-life.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'insurance',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-insurance.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'stocks',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-stocks.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'rewards',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-rewards.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'invest',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-unselected-state-inve.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'nav_more',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-unselected-state-more.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'nav_more_selected',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-tab-bar-selected-state-more.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'color_mode',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-color-mode.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'logout',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-logout.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'filter',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-filter.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'send-to-someone',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/send-to-someone.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'send-to-own-f',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-send-to-own-f.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'receive-money',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-receive-money.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'pay-loan',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/pay-loan.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'bills',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-bills.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'buy-goods',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-buy-goods.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'pay-card',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-card.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'buy-airtime',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-buy-airtime.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'buy-airtime-f',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-buy-airtime-f.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'send-money',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-send-money.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'withdraw',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-withdraw.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'salary',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-salary.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'add-note',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-add-note.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'add-account',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-add-account.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'account-security',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-account-security.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'bullet',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-bullet.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'show-password',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-show.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'show_balance',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-show-balance.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'hide-password',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-hide.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'password-check',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-check.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'square-check',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-checkbox.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'square-check-off',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-checkbox-off.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'sms',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-buy-airtime-f.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'email',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-email.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'navigation-chat',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-navigation-chat.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'mobile-wallet',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-mobile.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'send-to-equity',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-send-to-equity.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'cashcode',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-cashcode.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'other-bank',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-other-bank.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'paypal',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-paypal.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'headphones',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Support.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'phone-linked',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Phone-linked account.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'reorder',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-reorder.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'report-problem',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-report-problem.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'set-as-primary-account',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-set-as-primary.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'outlined-info',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-outlined-info.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'download',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Download.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'call',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Call.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'link',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Link.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'twitter',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Twitter.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'facebook',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Facebook.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'linkedin',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/LinkedIn.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'agent',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-agent.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'atm',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icons-atm.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'chevron-right',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-chevron-right.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'chevron-left',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-chevron-left.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'chevron-down',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-chevron-down.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'recommend',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Recommend app.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'data-privacy',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Data privacy.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'location',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Location.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'location',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Location.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'faq',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/FAQs.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'account-security',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Account security.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'pesalink-registration',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/visual-support-icon-pesalink-register.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'error-icon',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/error-snackbar-icon.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'information-icon',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Info.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'upload-documents',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/upload-document.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'delete-documents',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Delete.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'blocked-card',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/blocked-card.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'borrow-unselected',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Borrow_unselected.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'borrow-selected',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/Borrow_selected.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'cancel',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/delete-upload.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'upload',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/upload-icon.svg'
      )
    );
    this.matIconRegistry.addSvgIcon(
      'completed-upload',
      this.domSanitizer.bypassSecurityTrustResourceUrl(
        'assets/images/icons/tick-icon.svg'
      )
    );
  }
}


